/**
 * GENERATED by scripts/build-images.mjs — do not edit by hand.
 *
 * Maps an asset base path to the intrinsic size of its source and the derivative
 * widths that exist under /assets/opt. <OptImg> reads this to build a srcset and
 * to reserve layout space, so a caller only has to name the image and say how
 * wide it renders.
 *
 * Re-run the script after adding, replacing or removing anything under
 * public/assets/{figma-home,img,img/blogs}.
 */

export interface OptImageEntry {
  /** Intrinsic width of the source, in pixels. */
  w: number
  /** Intrinsic height of the source, in pixels. */
  h: number
  /** Derivative widths present on disk, ascending. */
  sizes: readonly number[]
}

export const OPT_IMAGES = {
  "figma-home/about-founder": {
    "w": 256,
    "h": 384,
    "sizes": [
      160,
      240,
      256
    ]
  },
  "figma-home/about-imgSubtract1": {
    "w": 656,
    "h": 498,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      656
    ]
  },
  "figma-home/about-man": {
    "w": 300,
    "h": 450,
    "sizes": [
      160,
      240,
      300
    ]
  },
  "figma-home/about-woman": {
    "w": 400,
    "h": 225,
    "sizes": [
      160,
      240,
      360,
      400
    ]
  },
  "figma-home/blogs-imgImage18": {
    "w": 1536,
    "h": 1024,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280,
      1536
    ]
  },
  "figma-home/footer-imgImage9": {
    "w": 433,
    "h": 576,
    "sizes": [
      160,
      240,
      360,
      433
    ]
  },
  "figma-home/hero-img4157844189182061": {
    "w": 3000,
    "h": 2000,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280,
      3000
    ]
  },
  "figma-home/hero-imgImage19": {
    "w": 1114,
    "h": 1412,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1114
    ]
  },
  "figma-home/hero-imgImage20": {
    "w": 1024,
    "h": 1024,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1024
    ]
  },
  "figma-home/hero-imgImage30": {
    "w": 1035,
    "h": 1126,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1035
    ]
  },
  "figma-home/hero-lifestyle": {
    "w": 1178,
    "h": 1470,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1178
    ]
  },
  "figma-home/image 19": {
    "w": 698,
    "h": 872,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      698
    ]
  },
  "figma-home/navbar-imgImage29": {
    "w": 500,
    "h": 500,
    "sizes": [
      160,
      240,
      360,
      480,
      500
    ]
  },
  "figma-home/partner-imgImage38": {
    "w": 1367,
    "h": 1151,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280,
      1367
    ]
  },
  "figma-home/products-imgFrame206-hover": {
    "w": 736,
    "h": 736,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      736
    ]
  },
  "figma-home/products-imgFrame206": {
    "w": 1346,
    "h": 1169,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280,
      1346
    ]
  },
  "figma-home/testimonials-imgFrame28": {
    "w": 1086,
    "h": 1448,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1086
    ]
  },
  "figma-home/testimonials-imgFrame29": {
    "w": 1200,
    "h": 1200,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1200
    ]
  },
  "figma-home/testimonials-imgFrame30": {
    "w": 675,
    "h": 1200,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      675
    ]
  },
  "figma-home/testimonials-imgFrame32": {
    "w": 736,
    "h": 1308,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      736
    ]
  },
  "figma-home/tracker-imgImage31": {
    "w": 512,
    "h": 512,
    "sizes": [
      160,
      240,
      360,
      480,
      512
    ]
  },
  "figma-home/tracker-imgImage32": {
    "w": 512,
    "h": 512,
    "sizes": [
      160,
      240,
      360,
      480,
      512
    ]
  },
  "figma-home/tracker-imgImage33": {
    "w": 512,
    "h": 512,
    "sizes": [
      160,
      240,
      360,
      480,
      512
    ]
  },
  "figma-home/why-imgImage22": {
    "w": 1024,
    "h": 1536,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1024
    ]
  },
  "figma-home/why-imgImage23": {
    "w": 676,
    "h": 369,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      676
    ]
  },
  "figma-home/why-imgImage24": {
    "w": 676,
    "h": 369,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      676
    ]
  },
  "figma-home/why-imgImage25": {
    "w": 676,
    "h": 369,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      676
    ]
  },
  "figma-home/why-imgImage26": {
    "w": 676,
    "h": 369,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      676
    ]
  },
  "img/blogs/body-image-social-media": {
    "w": 2718,
    "h": 1818,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280,
      2718
    ]
  },
  "img/blogs/cortisol-womens-health": {
    "w": 2718,
    "h": 1818,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280,
      2718
    ]
  },
  "img/blogs/first-period-india": {
    "w": 1280,
    "h": 808,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280
    ]
  },
  "img/blogs/hpv-awareness": {
    "w": 1280,
    "h": 808,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280
    ]
  },
  "img/blogs/menstrual-cup-vs-pad": {
    "w": 1280,
    "h": 808,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280
    ]
  },
  "img/blogs/panty-liner-vs-pad": {
    "w": 2718,
    "h": 1818,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280,
      2718
    ]
  },
  "img/blogs/pcos-pcod": {
    "w": 1280,
    "h": 808,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280
    ]
  },
  "img/blogs/period-fatigue": {
    "w": 2718,
    "h": 1818,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280,
      2718
    ]
  },
  "img/blogs/period-myths": {
    "w": 1280,
    "h": 808,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280
    ]
  },
  "img/blogs/prevent-rashes": {
    "w": 1280,
    "h": 808,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280
    ]
  },
  "img/blogs/sleep-womens-hormones": {
    "w": 2718,
    "h": 1818,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280,
      2718
    ]
  },
  "img/290mm": {
    "w": 2752,
    "h": 1536,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280,
      2752
    ]
  },
  "img/330mm": {
    "w": 2752,
    "h": 1536,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280,
      2752
    ]
  },
  "img/hero": {
    "w": 1200,
    "h": 1600,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1200
    ]
  },
  "img/pad-detail-1": {
    "w": 760,
    "h": 1012,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      760
    ]
  },
  "img/pad-detail-2": {
    "w": 760,
    "h": 1012,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      760
    ]
  },
  "img/prod-290-large3": {
    "w": 720,
    "h": 960,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      720
    ]
  },
  "img/prod-290-large9": {
    "w": 720,
    "h": 960,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      720
    ]
  },
  "img/prod-330-centre": {
    "w": 720,
    "h": 960,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      720
    ]
  },
  "img/prod-330-double": {
    "w": 720,
    "h": 960,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      720
    ]
  },
  "img/sample": {
    "w": 2400,
    "h": 1792,
    "sizes": [
      160,
      240,
      360,
      480,
      640,
      900,
      1280,
      2400
    ]
  }
} as const satisfies Record<string, OptImageEntry>

export type OptImageBase = keyof typeof OPT_IMAGES
