/**
 * Build the responsive image derivatives the site serves, and the manifest that
 * <OptImg> reads.
 *
 * Why pre-generate instead of using next/image: this app builds with
 * `output: 'standalone'` and deploys as a container, where the runtime optimiser
 * is an extra moving part — it needs sharp present in the runner stage and a
 * writable cache volume. Emitting plain files into `public/` keeps delivery a
 * static-file concern, satisfies the `img-src 'self'` CSP without widening it,
 * and costs nothing per request.
 *
 * This walks the asset directories rather than taking a hand-written list, so
 * adding an image to the design never means remembering to register it here.
 * The manifest it writes (src/lib/opt-images.ts) carries each source's intrinsic
 * size and the widths that actually exist on disk, which is what lets <OptImg>
 * emit a correct srcset and reserve layout space from just a base path.
 *
 * Run: node scripts/build-images.mjs
 * Output is deterministic — a re-run with unchanged sources produces no diff.
 */
import { mkdir, readdir, rm, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'

const ROOT = path.resolve(import.meta.dirname, '..')
const PUBLIC = path.join(ROOT, 'public')
const OUT = path.join(PUBLIC, 'assets/opt')
const MANIFEST = path.join(ROOT, 'src/lib/opt-images.ts')

/** Asset trees to walk, relative to public/assets. */
const TREES = ['figma-home', 'img', 'img/blogs']

/**
 * Width ladder. Covers a 360px phone at 1x/2x/3x through a 1280px desktop slot;
 * nothing on this site renders wider than that. Widths above a source's own
 * resolution are dropped rather than upscaled.
 */
const LADDER = [160, 240, 360, 480, 640, 900, 1280]

/** Below this, the original is already smaller than any derivative would be. */
const MIN_SOURCE_BYTES = 6 * 1024

const RASTER = /\.(png|jpe?g|webp)$/i

async function collect(tree) {
  const dir = path.join(PUBLIC, 'assets', tree)
  let entries
  try {
    entries = await readdir(dir, { withFileTypes: true })
  } catch {
    return []
  }
  return entries
    .filter((e) => e.isFile() && RASTER.test(e.name))
    .map((e) => ({ tree, name: e.name, abs: path.join(dir, e.name) }))
}

// Nested trees are listed explicitly, so drop anything a parent walk also saw.
const seen = new Set()
const sources = []
for (const tree of TREES) {
  for (const item of await collect(tree)) {
    if (seen.has(item.abs)) continue
    seen.add(item.abs)
    sources.push(item)
  }
}
sources.sort((a, b) => (a.tree + a.name).localeCompare(b.tree + b.name))

// Rebuild from scratch so a renamed or deleted source cannot leave a stale
// derivative behind that the manifest no longer mentions.
await rm(OUT, { recursive: true, force: true })

const manifest = {}
let sourceBytes = 0
let outBytes = 0
let skipped = 0

for (const { tree, name, abs } of sources) {
  const bytes = (await stat(abs)).size
  const base = `${tree}/${name.replace(/\.[a-z]+$/i, '')}`

  let meta
  try {
    meta = await sharp(abs).metadata()
  } catch {
    console.warn(`  unreadable, skipped: ${tree}/${name}`)
    continue
  }

  if (bytes < MIN_SOURCE_BYTES) {
    skipped += 1
    continue
  }

  const widths = LADDER.filter((w) => w < meta.width)
  // Always offer the source's own resolution as the top rung, so a design that
  // renders an asset at its full size is not silently downscaled.
  widths.push(meta.width)

  const alpha = Boolean(meta.hasAlpha)
  const emitted = []
  for (const w of widths) {
    const dest = path.join(OUT, `${base}-${w}.webp`)
    await mkdir(path.dirname(dest), { recursive: true })
    await sharp(abs)
      .resize({ width: w, kernel: 'lanczos3', withoutEnlargement: true })
      .webp({ quality: alpha ? 86 : 80, alphaQuality: 92, effort: 6 })
      .toFile(dest)
    emitted.push(w)
    outBytes += (await stat(dest)).size
  }

  sourceBytes += bytes
  manifest[base] = { w: meta.width, h: meta.height, sizes: emitted }
}

const header = `/**
 * GENERATED by scripts/build-images.mjs — do not edit by hand.
 *
 * Maps an asset base path to the intrinsic size of its source and the derivative
 * widths that exist under /assets/opt. <OptImg> reads this to build a srcset and
 * to reserve layout space, so a caller only has to name the image and say how
 * wide it renders.
 *
 * Re-run the script after adding, replacing or removing anything under
 * public/assets/{figma-home,img,img/blogs}.
 */

export interface OptImageEntry {
  /** Intrinsic width of the source, in pixels. */
  w: number
  /** Intrinsic height of the source, in pixels. */
  h: number
  /** Derivative widths present on disk, ascending. */
  sizes: readonly number[]
}

export const OPT_IMAGES = `

const body = JSON.stringify(manifest, null, 2)
await writeFile(
  MANIFEST,
  `${header}${body} as const satisfies Record<string, OptImageEntry>\n\nexport type OptImageBase = keyof typeof OPT_IMAGES\n`,
  'utf8',
)

for (const [base, entry] of Object.entries(manifest)) {
  console.log(
    `${base.padEnd(44)} ${String(entry.w).padStart(5)}x${String(entry.h).padEnd(5)} -> ${entry.sizes.join('/')}`,
  )
}

console.log(
  `\n${Object.keys(manifest).length} sources (${skipped} already small enough to leave alone)` +
    `\n${(sourceBytes / 1024 / 1024).toFixed(1)} MB of originals -> ${(outBytes / 1024 / 1024).toFixed(1)} MB of derivatives across every width` +
    `\nmanifest: ${path.relative(ROOT, MANIFEST)}`,
)
