-- Razorpay-managed subscription mandates.
--
-- Subscriptions move from pay-later renewals generated by cron to a Razorpay
-- MANDATE the customer's bank authorises once, after which the gateway owns the
-- billing calendar and each successful debit arrives as a `subscription.charged`
-- webhook that creates an order which is already paid.
--
-- Every column here is NULLABLE and every existing row keeps working. A row with
-- `razorpaySubscriptionId IS NULL` is a LEGACY pay-later plan and is still
-- renewed by `generateDueOrders`; that null-ness is the discriminator the
-- service branches on, which is what lets this deploy without stranding the
-- subscriptions that were already live.
--
-- NOTE ON THE ENUM: Postgres 12+ allows ALTER TYPE ... ADD VALUE outside a
-- transaction block, and `prisma migrate deploy` runs each statement file
-- accordingly. On Postgres 11 or earlier this file must be split into one
-- migration per added value. Aurora/Neon here are well past that.

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "SubscriptionStatus" ADD VALUE 'pending_mandate';
ALTER TYPE "SubscriptionStatus" ADD VALUE 'halted';

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "subscriptionId" TEXT;

-- AlterTable
ALTER TABLE "Subscription" ADD COLUMN     "chargeAmount" INTEGER,
ADD COLUMN     "currentEnd" TIMESTAMP(3),
ADD COLUMN     "gatewayStatus" TEXT,
ADD COLUMN     "mandateAuthedAt" TIMESTAMP(3),
ADD COLUMN     "razorpayCustomerId" TEXT,
ADD COLUMN     "razorpayPlanId" TEXT,
ADD COLUMN     "razorpaySubscriptionId" TEXT,
ADD COLUMN     "resumeAt" TIMESTAMP(3);

-- CreateTable
CREATE TABLE "RazorpayPlan" (
    "id" TEXT NOT NULL,
    "fingerprint" TEXT NOT NULL,
    "razorpayPlanId" TEXT NOT NULL,
    "amount" INTEGER NOT NULL,
    "period" TEXT NOT NULL,
    "interval" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RazorpayPlan_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "RazorpayPlan_fingerprint_key" ON "RazorpayPlan"("fingerprint");

-- CreateIndex
CREATE UNIQUE INDEX "RazorpayPlan_razorpayPlanId_key" ON "RazorpayPlan"("razorpayPlanId");

-- CreateIndex
CREATE INDEX "Order_subscriptionId_idx" ON "Order"("subscriptionId");

-- CreateIndex
CREATE UNIQUE INDEX "Subscription_razorpaySubscriptionId_key" ON "Subscription"("razorpaySubscriptionId");

-- CreateIndex
CREATE INDEX "Subscription_status_resumeAt_idx" ON "Subscription"("status", "resumeAt");

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_subscriptionId_fkey" FOREIGN KEY ("subscriptionId") REFERENCES "Subscription"("id") ON DELETE SET NULL ON UPDATE CASCADE;

